# Generated by Django 4.1 on 2022-09-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.CharField(max_length=500)),
                ("labels", models.CharField(max_length=9000)),
                ("name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="MetaFile",
            fields=[
                (
                    "id",
                    models.CharField(max_length=600, primary_key=True, serialize=False),
                ),
            ],
        ),
    ]
